/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function greet(): void;
export function init(): void;
export function __wbg_staticaabb2dindex_free(a: number): void;
export function staticaabb2dindex_new(a: number, b: number, c: number): number;
export function staticaabb2dindex_query(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function staticaabb2dindex_levelBounds(a: number): number;
export function staticaabb2dindex_allBoxes(a: number): number;
export function staticaabb2dindex_neighbors(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function __wbg_polyline_free(a: number): void;
export function polyline_new(a: number, b: number, c: number): number;
export function polyline_add(a: number, b: number, c: number, d: number): void;
export function polyline_clear(a: number): void;
export function polyline_length(a: number): number;
export function polyline_cycleVertexes(a: number, b: number): void;
export function polyline_vertexData(a: number, b: number): void;
export function polyline_is_closed(a: number): number;
export function polyline_set_is_closed(a: number, b: number): void;
export function polyline_area(a: number): number;
export function polyline_pathLength(a: number): number;
export function polyline_scale(a: number, b: number): void;
export function polyline_translate(a: number, b: number, c: number): void;
export function polyline_windingNumber(a: number, b: number, c: number): number;
export function polyline_boolean(a: number, b: number, c: number): number;
export function polyline_closestPoint(a: number, b: number, c: number): number;
export function polyline_createApproxSpatialIndex(a: number): number;
export function polyline_createSpatialIndex(a: number): number;
export function polyline_extents(a: number, b: number): void;
export function polyline_invertDirection(a: number): void;
export function polyline_parallelOffset(a: number, b: number, c: number): number;
export function polyline_rawOffset(a: number, b: number): number;
export function polyline_rawOffsetSegs(a: number, b: number): number;
export function polyline_selfIntersects(a: number): number;
export function polyline_arcsToApproxLines(a: number, b: number): number;
export function polyline_arcsToApproxLinesData(a: number, b: number, c: number): void;
export function polyline_testProperties(a: number): number;
export function polyline_logToConsole(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_start(): void;
